// Assembly of the model input: the diff plus the human context around the PR
// (its current description and the whole comment thread). Kept dependency-free
// so it can be unit-tested without @actions/* or network access.

const AUTO_DESCRIPTION_MARKER = '> `AUTO DESCRIPTION`';
const ORIGINAL_DESCRIPTION_PREFIX = '**Original description**:';

// gpt-5.6 models have a 400k-token context window; these budgets keep a typical
// PR untruncated while bounding pathological cases (huge diffs, 100+ comments).
const MAX_DIFF_LENGTH = 100000;
const MAX_DESCRIPTION_LENGTH = 5000;
const MAX_COMMENTS_LENGTH = 20000;
const MAX_SINGLE_COMMENT_LENGTH = 2000;

const SYSTEM_PROMPT = `You write GitHub pull request descriptions.

The user message has up to three sections:
- <diff> — the git diff. This is the source of truth for WHAT changed.
- <current_description> — the description the PR has right now. It may be an earlier auto-generated one (marked as such) or written by a human.
- <comments> — the PR conversation: review comments, inline code comments, and the archived original description.

Use the diff for what changed, and the description and comments for intent: why the change was made, ticket links, decisions taken, reviewer concerns already addressed.

Rules:
- Preserve human-authored facts worth keeping: ticket/issue links, test plans, deployment or rollout notes, explicit caveats. Do not invent any of these.
- Do not restate reviewer comments as if they were features. Reflect them only when they explain the change or note a resolved concern.
- If the current description was auto-generated, rewrite it from scratch rather than editing it in place.
- Ignore stale statements that the diff contradicts.

Produce the PR description body in GitHub Markdown:
- Start with a 1-2 sentence summary of the change.
- Group the changes into sections with emoji headings (e.g. ✨ Features, 🐛 Fixes, 🔧 Maintenance); include only sections that apply.
- Describe user-visible impact, not file-by-file mechanics.

Output only the description body — no title, no preamble, no code fences around the whole answer.`;

/**
 * Truncate text to a maximum length, appending a visible marker when cut.
 * @param {string} text
 * @param {number} max
 * @param {string} [label] word used in the truncation marker
 * @returns {string}
 */
function truncate(text, max, label = 'content') {
  if (typeof text !== 'string' || text.length <= max) return text || '';
  return `${text.substring(0, max)}\n... [${label} truncated]`;
}

/**
 * Is this PR body one the action generated on an earlier run?
 * @param {string} body
 * @returns {boolean}
 */
function isAutoGeneratedDescription(body) {
  return typeof body === 'string' && body.trimStart().startsWith(AUTO_DESCRIPTION_MARKER);
}

/**
 * Render the collected comments as a plain-text block for the model.
 * Inline review comments carry their file/line so the model can tie them to the diff.
 * @param {Array<{kind: string, author: string, body: string, path?: string, line?: number}>} comments
 * @returns {string} empty string when there is nothing worth sending
 */
function formatComments(comments) {
  if (!Array.isArray(comments) || comments.length === 0) return '';

  const rendered = [];
  let used = 0;
  let skipped = 0;

  for (const comment of comments) {
    const body = (comment && typeof comment.body === 'string' ? comment.body : '').trim();
    if (!body) continue;

    const author = comment.author || 'unknown';
    const location = comment.path
      ? ` on ${comment.path}${comment.line ? `:${comment.line}` : ''}`
      : '';
    const entry = `[${comment.kind || 'comment'}] @${author}${location}:\n${truncate(body, MAX_SINGLE_COMMENT_LENGTH, 'comment')}`;

    if (used + entry.length > MAX_COMMENTS_LENGTH) {
      skipped += 1;
      continue;
    }

    rendered.push(entry);
    used += entry.length;
  }

  if (rendered.length === 0) return '';
  if (skipped > 0) {
    rendered.push(`... [${skipped} further comment(s) omitted to stay within the context budget]`);
  }

  return rendered.join('\n\n---\n\n');
}

/**
 * Build the user message: diff plus whatever context is available.
 * @param {{diff: string, currentDescription?: string, comments?: Array}} input
 * @returns {string}
 */
function buildUserMessage({ diff, currentDescription = '', comments = [] }) {
  const sections = [`<diff>\n${truncate(diff, MAX_DIFF_LENGTH, 'diff')}\n</diff>`];

  const description = (currentDescription || '').trim();
  if (description) {
    const origin = isAutoGeneratedDescription(description)
      ? 'auto-generated on an earlier run — rewrite, do not edit in place'
      : 'written by a human — preserve the intent and any links or notes worth keeping';
    sections.push(
      `<current_description origin="${origin}">\n${truncate(description, MAX_DESCRIPTION_LENGTH, 'description')}\n</current_description>`
    );
  }

  const commentsText = formatComments(comments);
  if (commentsText) {
    sections.push(`<comments>\n${commentsText}\n</comments>`);
  }

  return sections.join('\n\n');
}

module.exports = {
  AUTO_DESCRIPTION_MARKER,
  ORIGINAL_DESCRIPTION_PREFIX,
  MAX_DIFF_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MAX_COMMENTS_LENGTH,
  MAX_SINGLE_COMMENT_LENGTH,
  SYSTEM_PROMPT,
  truncate,
  isAutoGeneratedDescription,
  formatComments,
  buildUserMessage,
};
