const test = require('node:test');
const assert = require('node:assert');

const {
  AUTO_DESCRIPTION_MARKER,
  MAX_DIFF_LENGTH,
  MAX_COMMENTS_LENGTH,
  MAX_SINGLE_COMMENT_LENGTH,
  SYSTEM_PROMPT,
  truncate,
  isAutoGeneratedDescription,
  formatComments,
  buildUserMessage,
} = require('../context');

const DIFF = 'diff --git a/app.rb b/app.rb\n+puts "hi"';

test('buildUserMessage always includes the diff', () => {
  const msg = buildUserMessage({ diff: DIFF });
  assert.match(msg, /<diff>/);
  assert.match(msg, /puts "hi"/);
  assert.doesNotMatch(msg, /<current_description/);
  assert.doesNotMatch(msg, /<comments>/);
});

test('buildUserMessage includes a human-written description as intent', () => {
  const msg = buildUserMessage({
    diff: DIFF,
    currentDescription: 'Fixes FIN-1160. Deploy after the migration.',
  });
  assert.match(msg, /<current_description origin="written by a human/);
  assert.match(msg, /Fixes FIN-1160/);
  assert.match(msg, /Deploy after the migration/);
});

test('buildUserMessage flags a previously auto-generated description for rewrite', () => {
  const previous = `${AUTO_DESCRIPTION_MARKER}\n> by [auto-pr-description-action](x)\n\n## ✨ Features\n- old text`;
  const msg = buildUserMessage({ diff: DIFF, currentDescription: previous });
  assert.match(msg, /origin="auto-generated on an earlier run/);
  assert.match(msg, /rewrite, do not edit in place/);
});

test('buildUserMessage includes comments, with file and line for inline ones', () => {
  const msg = buildUserMessage({
    diff: DIFF,
    comments: [
      { kind: 'comment', author: 'yuri-val', body: 'Please keep the API contract stable.' },
      { kind: 'review comment', author: 'reviewer', body: 'Guard the nil case', path: 'app/models/user.rb', line: 42 },
      { kind: 'review:approved', author: 'mpiatkivskij', body: 'LGTM' },
    ],
  });
  assert.match(msg, /<comments>/);
  assert.match(msg, /\[comment\] @yuri-val:/);
  assert.match(msg, /API contract stable/);
  assert.match(msg, /\[review comment\] @reviewer on app\/models\/user\.rb:42:/);
  assert.match(msg, /\[review:approved\] @mpiatkivskij:/);
});

test('the archived original description comment survives into the context', () => {
  const msg = buildUserMessage({
    diff: DIFF,
    currentDescription: `${AUTO_DESCRIPTION_MARKER}\n\nregenerated`,
    comments: [{ kind: 'comment', author: 'github-actions[bot]', body: '**Original description**:\n\nCloses FIN-1214, needs QA on prod data.' }],
  });
  assert.match(msg, /Original description/);
  assert.match(msg, /Closes FIN-1214/);
});

test('empty and whitespace-only content is skipped', () => {
  const msg = buildUserMessage({
    diff: DIFF,
    currentDescription: '   \n  ',
    comments: [
      { kind: 'comment', author: 'a', body: '' },
      { kind: 'comment', author: 'b', body: '   ' },
      { kind: 'review:commented', author: 'c', body: null },
    ],
  });
  assert.doesNotMatch(msg, /<current_description/);
  assert.doesNotMatch(msg, /<comments>/);
});

test('formatComments tolerates malformed input', () => {
  assert.strictEqual(formatComments(null), '');
  assert.strictEqual(formatComments([]), '');
  assert.strictEqual(formatComments([{}]), '');
  assert.match(formatComments([{ body: 'no author' }]), /@unknown/);
});

test('a single oversized comment is truncated, not dropped', () => {
  const long = 'x'.repeat(MAX_SINGLE_COMMENT_LENGTH + 500);
  const out = formatComments([{ kind: 'comment', author: 'a', body: long }]);
  assert.match(out, /\[comment truncated\]/);
  assert.ok(out.length < MAX_SINGLE_COMMENT_LENGTH + 300);
});

test('the comment budget is respected and the omission is disclosed', () => {
  const many = Array.from({ length: 60 }, (_, i) => ({
    kind: 'comment',
    author: `user${i}`,
    body: 'y'.repeat(MAX_SINGLE_COMMENT_LENGTH),
  }));
  const out = formatComments(many);
  assert.ok(out.length <= MAX_COMMENTS_LENGTH + 200, `budget exceeded: ${out.length}`);
  assert.match(out, /further comment\(s\) omitted/);
});

test('an oversized diff is truncated', () => {
  const huge = 'z'.repeat(MAX_DIFF_LENGTH + 1000);
  const msg = buildUserMessage({ diff: huge });
  assert.match(msg, /\[diff truncated\]/);
});

test('truncate leaves short text untouched', () => {
  assert.strictEqual(truncate('short', 100), 'short');
  assert.strictEqual(truncate('', 10), '');
  assert.strictEqual(truncate(undefined, 10), '');
});

test('isAutoGeneratedDescription detects the marker, including leading whitespace', () => {
  assert.ok(isAutoGeneratedDescription(`${AUTO_DESCRIPTION_MARKER}\nbody`));
  assert.ok(isAutoGeneratedDescription(`\n  ${AUTO_DESCRIPTION_MARKER}\nbody`));
  assert.ok(!isAutoGeneratedDescription('Written by a person'));
  assert.ok(!isAutoGeneratedDescription(''));
  assert.ok(!isAutoGeneratedDescription(undefined));
});

test('the system prompt tells the model how to use each section', () => {
  for (const marker of ['<diff>', '<current_description>', '<comments>']) {
    assert.ok(SYSTEM_PROMPT.includes(marker), `prompt should document ${marker}`);
  }
  assert.match(SYSTEM_PROMPT, /source of truth/);
  assert.match(SYSTEM_PROMPT, /ticket/i);
});

test('section order is diff, description, comments', () => {
  const msg = buildUserMessage({
    diff: DIFF,
    currentDescription: 'human text',
    comments: [{ kind: 'comment', author: 'a', body: 'a comment' }],
  });
  assert.ok(msg.indexOf('<diff>') < msg.indexOf('<current_description'));
  assert.ok(msg.indexOf('<current_description') < msg.indexOf('<comments>'));
});
